# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileClient2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MobileClient2
#  pod 'BraintreeDropIn'

  #target 'MobileClient2-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  target 'MobileClient2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MobileClient2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MobileClient2-tvOS

  target 'MobileClient2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
