
export const SIGN = {
  //SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL: 'SIGN_IN_FAIL',
  SIGN_OUT: 'SIGN_OUT',
  //SIGN_UP: 'SIGN_UP',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL: 'SIGN_UP_FAIL',
};

export const WS = {
  SIGN_IN: 'WS_SIGN_IN',
  SIGN_IN_RESPONSE: 'WS_SIGN_IN_RESPONSE',
  SIGN_IN_RESPONSE_COMPLETED: 'WS_SIGN_IN_RESPONSE_COMPLETED',

  SIGN_UP: 'WS_SIGN_UP',
  SIGN_UP_RESPONSE: 'WS_SIGN_UP_RESPONSE',
  SIGN_UP_RESPONSE_COMPLETED: 'WS_SIGN_UP_RESPONSE_COMPLETED',

  SUBMIT_NORMAL_ORDER: 'WS_SUBMIT_NORMAL_ORDER',
  SUBMIT_NORMAL_ORDER_RESPONSE: 'WS_SUBMIT_NORMAL_ORDER_RESPONSE',
  SUBMIT_NORMAL_ORDER_RESPONSE_COMPLETED: 'WS_SUBMIT_NORMAL_ORDER_RESPONSE_COMPLETED',
  SUBMIT_EDIT_NORMAL_ORDER: 'WS_SUBMIT_EDIT_NORMAL_ORDER',
  SUBMIT_EDIT_NORMAL_ORDER_RESPONSE: 'WS_SUBMIT_EDIT_NORMAL_ORDER_RESPONSE',
  SUBMIT_EDIT_NORMAL_ORDER_RESPONSE_COMPLETED: 'WS_SUBMIT_EDIT_NORMAL_ORDER_RESPONSE_COMPLETED',

  JOIN_ORDER: 'WS_JOIN_ORDER',
  JOIN_ORDER_RESPONSE: 'WS_JOIN_ORDER_RESPONSE',
  JOIN_ORDER_RESPONSE_COMPLETED: 'WS_JOIN_ORDER_RESPONSE_COMPLETED',

  LEAVE_JOIN_ORDER: 'WS_LEAVE_JOIN_ORDER',
  LEAVE_JOIN_ORDER_RESPONSE: 'WS_LEAVE_JOIN_ORDER_RESPONSE',
  LEAVE_JOIN_ORDER_RESPONSE_COMPLETED: 'WS_LEAVE_JOIN_ORDER_RESPONSE_COMPLETED',

  COMPLETE_ORDER: 'WS_COMPLETE_ORDER',
  COMPLETE_ORDER_RESPONSE: 'WS_COMPLETE_ORDER_RESPONSE',
  COMPLETE_ORDER_RESPONSE_COMPLETED: 'WS_COMPLETE_ORDER_RESPONSE_COMPLETED',

  SET_PAYMENT_METHOD: 'WS_SET_PAYMENT_METHOD',
  SET_PAYMENT_METHOD_RESPONSE: 'WS_SET_PAYMENT_METHOD_RESPONSE',
  SET_PAYMENT_METHOD_RESPONSE_COMPLETED: 'WS_SET_PAYMENT_METHOD_RESPONSE_COMPLETED',

  CHANGE_TRANSITION_STATUS: 'WS_CHANGE_TRANSITION_STATUS',
  CHANGE_TRANSITION_STATUS_RESPONSE: 'WS_CHANGE_TRANSITION_STATUS_RESPONSE',
  CHANGE_TRANSITION_STATUS_RESPONSE_COMPLETED: 'WS_CHANGE_TRANSITION_STATUS_RESPONSE_COMPLETED',

  CHANGE_ARRIVAL_STATUS: 'WS_CHANGE_ARRIVAL_STATUS',
  CHANGE_ARRIVAL_STATUS_RESPONSE: 'WS_CHANGE_ARRIVAL_STATUS_RESPONSE',
  CHANGE_ARRIVAL_STATUS_RESPONSE_COMPLETED: 'WS_CHANGE_ARRIVAL_STATUS_RESPONSE_COMPLETED',

  GET_USER_ORDERS: 'WS_GET_USER_ORDERS',
  GET_USER_ORDERS_RESPONSE: 'WS_GET_USER_ORDERS_RESPONSE',
  GET_USER_ORDERS_RESPONSE_COMPLETED: 'WS_GET_USER_ORDERS_RESPONSE_COMPLETED',

  GET_AVAILABLE_ORDERS: 'WS_GET_AVAILABLE_ORDERS',
  GET_AVAILABLE_ORDERS_RESPONSE: 'WS_GET_AVAILABLE_ORDERS_RESPONSE',
  GET_AVAILABLE_ORDERS_RESPONSE_COMPLETED: 'WS_GET_AVAILABLE_ORDERS_RESPONSE_COMPLETED',

  GET_SHARE_ORDERS: 'WS_GET_SHARE_ORDERS',
  GET_SHARE_ORDERS_RESPONSE: 'WS_GET_SHARE_ORDERS_RESPONSE',
  GET_SHARE_ORDERS_RESPONSE_COMPLETED: 'WS_GET_SHARE_ORDERS_RESPONSE_COMPLETED',

  CANCEL_ORDER: 'WS_CANCEL_ORDER',
  CANCEL_ORDER_RESPONSE: 'WS_CANCEL_ORDER_RESPONSE',
  CANCEL_ORDER_RESPONSE_COMPLETED: 'WS_CANCEL_ORDER_RESPONSE_COMPLETED',

  UPDATE_USER_PROFILE: 'WS_UPDATE_USER_PROFILE',
  UPDATE_USER_PROFILE_RESPONSE: 'WS_UPDATE_USER_PROFILE_RESPONSE',
  UPDATE_USER_PROFILE_COMPLETED: 'WS_UPDATE_USER_PROFILE_COMPLETED',

  ACCEPT_ORDER: 'WS_ACCEPT_ORDER',
  ACCEPT_ORDER_RESPONSE: 'WS_ACCEPT_ORDER_RESPONSE',
  ACCEPT_ORDER_RESPONSE_COMPLETED: 'WS_ACCEPT_ORDER_RESPONSE_COMPLETED',

  GET_ACCEPT_HISTORY_ORDERS: 'WS_GET_ACCEPT_HISTORY_ORDERS',
  GET_ACCEPT_HISTORY_ORDERS_RESPONSE: 'WS_GET_ACCEPT_HISTORY_ORDERS_RESPONSE',
  GET_ACCEPT_HISTORY_ORDERS_RESPONSE_COMPLETED: 'WS_GET_ACCEPT_HISTORY_ORDERS_RESPONSE_COMPLETED',
};

export const PAGE = {
  ATTACH_MAIN_NAVIGATION: 'ATTACH_MAIN_NAVIGATION',
  ATTACH_TAB_NAVIGATION: 'ATTACH_TAB_NAVIGATION',
  MAP_RESULT_NAVI_BACK: 'MAP_RESULT_NAVI_BACK',
  MAP_RESULT_NAVI_BACK_CLEAR: 'MAP_RESULT_NAVI_BACK_CLEAR',
};

export const ORDER = {
  // UPDATE_OPENED_ORDER: 'UPDATE_OPENED_ORDER',
  // UPDATE_OPENED_ORDER_COMPLETED: 'UPDATE_OPENED_ORDER_COMPLETED',
  // CANCEL_UPDATE_OPENED_ORDER: 'CANCEL_UPDATE_OPENED_ORDER',
  // CANCEL_UPDATE_OPENED_ORDER_COMPLETED: 'CANCEL_UPDATE_OPENED_ORDER_COMPLETED',
  CANCEL_ORDER_SUCCESS: 'CANCEL_ORDER_SUCCESS',
  CANCEL_ORDER_FAIL: 'CANCEL_ORDER_FAIL',
  SUBMIT_NORMAL_ORDER_SUCCESS: 'SUBMIT_NORMAL_ORDER_SUCCESS',
  SUBMIT_NORMAL_ORDER_FAIL: 'SUBMIT_NORMAL_ORDER_FAIL',
  SUBMIT_EDIT_NORMAL_ORDER_SUCCESS: 'SUBMIT_EDIT_NORMAL_ORDER_SUCCESS',
  SUBMIT_EDIT_NORMAL_ORDER_FAIL: 'SUBMIT_EDIT_NORMAL_ORDER_FAIL',
}
